version: '3.4'

networks:
   default:
     name: 'graphql-demo-network'

services:
  moviecatalog.api:
    image: ${DOCKER_REGISTRY-}movie-catalog.api
    container_name: movie-catalog.api
    ports:
      - 32741:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: MovieCatalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      SQL_CONNECTION_STRING: "Server=sqlserver; Database=MovieCatalog; Encrypt=True; TrustServerCertificate=True; User ID=sa; Password=comPL3x-p4SSw0rd"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - 2368:1433
    restart: always
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      ACCEPT_EULA: "y"
      MSSQL_SA_PASSWORD: "comPL3x-p4SSw0rd"

volumes:
  sqlvolume:
